<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <!-- This sample requires experimental Windows App SDK for custom XAML condition support. -->
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="2.4.1-experimental" />
    <PackageVersion Include="Microsoft.Windows.CppWinRT" Version="3.0.260818.1" />
  </ItemGroup>
</Project>
