<Project>
  <Import Project="..\Directory.Packages.props" />

  <ItemGroup>
    <!-- WindowsML-specific dependencies -->
    <PackageVersion Include="Microsoft.ML.OnnxRuntimeGenAI.WinML" Version="0.14.0" />
    <PackageVersion Include="Microsoft.Windows.AbiWinRT" Version="2.0.210330.2" />
  </ItemGroup>
</Project>