namespace WinUI3TemplateCpp
{
    [default_interface]
    runtimeclass MainPage : Microsoft.UI.Xaml.Controls.Page
    {
        MainPage();
        static MainPage Current();
        // To make these methods accesible to others XAML pages, it's needed to define them on the IDL
        void NotifyUser(String strMessage, Microsoft.UI.Xaml.Controls.InfoBarSeverity severity, Boolean isOpen);
    }

    // To use Scenario in a winrt::Windows::Foundation::Collections::IVector<Scenario>, Scenario should be a WinRT type
    struct Scenario
    {
        String Title;
        String ClassName;
    };
}
